
document.getElementById("myNav").innerHTML =
        "<div class='head'>"
            +"<div class='head-item'>"
                +"<a class='navbar-brand' href='https://www.tvz.hr'>"
                    +"<img src='../img/TvzLogo.png' alt='tvzLogo' style='width: 100px;'>"
                +"</a>"
            +"</div>"
            +"<div class='head-item'>"
                +"<h2>Metro SCSS library</h2>"
            +"</div>"
            +"<div class='head-item'>"

                +"<div class='hamburger'>"
                    +"<div class='burger burger-3' id='burger'>"
                        +"<input type='checkbox' name='burger3' id='mainNav' onclick='mainNavigation()' />"
                        +"<label for='mainNav'>"
                            +"<span class='bar bar-1'></span>"
                            +"<span class='bar bar-2'></span>"
                            +"<span class='bar bar-3'></span>"
                        +"</label>"
                    +"</div>"
                +"</div>"
            +"</div>"
        +"</div>"

        +"<nav id='mainSidebar' class='mainSidebar'>"
            +"<div class='sidebar-item nav'>"
                +"<ul>"
                    +"<li><a href='../index.html'>Get started</a></li>"

                    +"<li><span class='tp-1'>Layaout</span></li>"
                    +"<li><a href='../html/grid.html'>Grid</a></li>"
                    +"<li><a href='../html/columns.html'>Columns</a></li>"
                    +"<li><a href='flex'><span class='td-0'>Flex</span></a></li>"
        
                    +"<li><span class='tp-1'>Content</span></li>"
                    +"<li><a href='../html/typography.html'>Typography</a></li>"
                    +"<li><a href='../html/colors.html'>Colors</a></li>"
                    +"<li><a href='../html/images.html'>Images</a></li>"
                    +"<li><a href='../html/table.html'>Table</a></li>"
                    +"<li><a href='../html/input.html'>Input</a></li>"
                    +"<li><a href='../html/carousel.html'>Carousel</a></li>"

                    +"<li><span class='tp-1'>Navigation menu's</span></li>"
                    +"<li><a href='../html/navigationMenu.html'>Side menu</a></li>"
                    +"<li><a href='../html/navbar.html'>Top menu</a></li>"
                    +"<li><a href='../html/breadcrumb.html'>Breadcrumb</a></li>"

                    +"<li><span class='tp-1'>Components</span></li>" 
                    +"<li><a href='../html/hamburgerIcon.html'>Hamburger icon</a></li>"
                    +"<li><a href='../html/collapse.html'>Collapse</a></li>"
                    +"<li><a href='../html/form.html'>Form's</a></li>"
                    +"<li><a href='../html/cards.html'>Card's</a></li>"
                    +"<li><a href='../html/buttons.html'>Button's</a></li>"
                    +"<li><a href='../html/modal.html'>Modal</a></li>"
                    +"<li><a href='../html/progressBar.html'>Progress bar</a></li>"
                    // +"<li><a href='../html/pagination.html'>Pagination</a></li>"
                    
                    +"<li><span class='tp-1'>Utilities</span></li>"              
                    +"<li><a href='../html/visability.html'>Visability</a></li>"
                    +"<li><a href='../html/shadow.html'>Shadows</a></li>"
                    +"<li><a href='../html/float.html'>Float & Clearfix</a></li>"
                    +"<li><a href='../html/tooltip.html'>Tooltip</a></li>"
                    +"<li><a href='../html/scrollspy.html'>Scrollspy</a></li>"
                    +"<li><a href='../html/borders.html'>Borders</a></li>"		
                    +"<li><a href='../html/position'><span class='td-0'>Position</span></a></li>"
                    +"<li><a href='../html/sizing'><span class='td-0'>Sizing</span></a></li>"	
                +"</ul>"
            +"</div>"
        +"</nav>";
